lemmy:
  instanceConfig:
    - instance:
        id: "test-instance"
        url: "https://enterprise.lemmy.ml"
        credentials:
          username: "JohnDoe"
          password_file: "/path/to/password_file.pem" 
          private_key_file: "/path/to/private_key.pem"